mosviz/loaders/mos_loaders.py
I added a loader for the NIRCam simulated image, should work just as well for a cutout or the full image as long as the data is stored in the FITS file the same way.
=> Nircam loader

mosviz/loaders/mos_loaders.py
Note: The 2D spectra are in separate files so the loader only loads either the red or blue, but the 1D spectra have the red and the blue in the same file so I concatenate them and give the full spectrum to the Data object.
=> Added loaders for DEIMOS spectra and their ACS cutouts

mosviz/loaders/mos_loaders.py, mosviz/viewers/mos_viewer.py
With the newest glue, Data has a .meta attribute so we can get the loader names from the catalog header.  I've set it so that MOSViz checks for the loaders first in .glue/config.py then in mosviz/loaders/mos_loaders.py and if it can't find the loader (or one isn't specified) it tries to use JWST loaders.
=> Agnostic loader

docs/readingindata.rst, mosviz/loaders/loader_selection.py, mosviz/loaders/loader_selection.ui, mosviz/viewers/mos_viewer.py, mosviz/widgets/plots.py
The slit is back:
Note that I am assuming the ``ra`` and ``dec`` columns in the table give the origin of the slit (not of the source). If this is not an assumption we want to make, we should require ``slit_ra`` and ``slit_dec`` to be specified in the table (since we don't care about the actual source position).
We're also assuming for now that the RA/Dec are given in FK5/J2000
I've also removed the variable slit angle that I had added in the previous pull request, which simplifies things in terms of plotting.
=> Refactor slit-plotting code

mosviz/compat.py, mosviz/loaders/loader_selection.py, mosviz/loaders/mos_loaders.py, mosviz/viewers/mos_viewer.py, mosviz/widgets/plots.py, mosviz/widgets/share_axis.py, mosviz/widgets/toolbars.py, mosviz/widgets/viewer_options.py
This fixes the locking of axes. As a result, for now, the y-axis of the 2D spectrum is just displacement in pixels. The issue is that if the 2D spectrum uses WCSAxes then the spectral axis locking doesn't work because the x values for the 2D spectrum are in pixels and the x values for the 1D spectrum are in world coordinates.
Note that this now relies on the developer of Glue to work correctly. I will release glue v0.10.5 soon with the required fixes, but I think we can already merge this if it otherwise looks good.
One of the things that this PR does is to switch from using private API access in matplotlib for sharing axes to relying on the fully public API. This adds a little code in ``share_axis.py`` but I'm more comfortable relying on public APIs.
=> Fix locking of axes

mosviz/viewers/mos_viewer.py, mosviz/widgets/plots.py
This makes a few small improvements (some as a result of speaking with @kassin today)
* Make it so that the 1D and 2D spectra have axes that line up exactly
* Make it so that the vertical splitter on the left and the right are linked, to make sure the image axes always line up exactly with the 2D spectrum
* Rename MosViz to MOSViz in viewer list
More improvements coming soon
=> WIP: Minor ui improvements

setup.py
@astrofrog's spiffy data loader designer file was not being picked up via the install process.
=> Include loader ui file in install

mosviz/viewers/mos_viewer.py
This PR fixes an issue where selection events in other viewers were not being properly propagated to the MOSViz viewer.
=> Subset messages were not being propagated

setup.cfg
This is necessary to allow building the astroconda package since glueviz was changed to a metapackage.
=> Change glueviz dependency to glue-core.

appveyor.yml, mosviz/viewers/mos_viewer.py
The previous specviz import didn't work with the latest stable version of specviz so the 'Open in specviz' button didn't work.
Also Fixes #90
=> Fix specviz import

mosviz/data/ui/loader_selection.ui, mosviz/loaders/loader_selection.py, mosviz/viewers/mos_viewer.py
This fixes compatibility with the latest developer version of glue - before this MOSViz was relying on a private attribute for which no backward-compatibility is guaranteed.
=> Use the public API to get categorical labels

mosviz/startup.py
This looks like:
I thought it would make sense to include 'powered by glue', but let me know if you disagree.
Fixes https://github.com/spacetelescope/mosviz/issues/102
=> Include MOSViz in window title

mosviz/_astropy_init.py, mosviz/loaders/__init__.py, mosviz/loaders/loader_selection.py, mosviz/loaders/utils.py, mosviz/plugins/__init__.py, mosviz/plugins/cutout_tool.py, mosviz/plugins/table_generator.py, mosviz/startup.py, mosviz/viewers/__init__.py, mosviz/viewers/mos_viewer.py, mosviz/widgets/__init__.py, mosviz/widgets/plots.py, mosviz/widgets/share_axis.py, mosviz/widgets/toolbars.py, mosviz/widgets/viewer_options.py, setup.py
This resolves #109. ~It also adds tests for Python 3.7 to the CI configs.~ We can't add tests for 3.7 until   particular dependencies (e.g. `specutils`) provide wheels for 3.7.
=> Remove support for Python 2.7

mosviz/conftest.py, mosviz/viewers/tests/test_mos_viewer.py
This is a small change but it allows developers to write tests with a reset state of MOSViz each time.
=> State resets after each test method

mosviz/tests/data/deimos_mosviz.tbl, mosviz/viewers/mos_viewer.py, mosviz/widgets/plots.py
Closes #80 
This PR introduces code that handles selections with no spectra (1D and/or 2D). It also adds a line to the deimos table that has `None` for the cutout, spectrum 1D and spectrum 2D.
**Selection without a cutout, spectrum 1D and spectrum 2D:**
MOSViz Table line: `deimos_None 214.49056 52.632246 None None None 0.2 3.3 0.66`
MOSVIz Viewer:
CC: @hcferguson @kassin
=> Handle selections with only one type of spectra

mosviz/_astropy_init.py
This one-line change prevents pytest from picking up the test function as a test. See astropy/package-template#373.
*This is an automated fix by @pllim. If this is opened in error, please close without merge.*
=> Prevent pytest from picking up test function as a test

.travis.yml
The travis testing against numpy=1.11 and astropy=3.0 is not correct, the test should be against stable. This is after a discussion with @drdavella who had seen this before. 
Fixes #173
=> Removed old dependency test for numpy and astropy

.travis.yml, docs/conf.py, tox.ini
This resolves #162 by adding tests to the CI matrix for both Py36 and Py37.
It also performs some cleanup on the doc build in order to allow it to run without the need for `astropy_helpers`. The doc build gets tested as part of the CI run.
=> Update CI matrix, use tox for testing

mosviz/loaders/jwst_loaders.py
@robelgeda - this fixes the issue you were seeing with loading NIRSpec. Basically the data objects always need to have a ``.coords`` attribute set now.
=> Set coords attribute on NIRSpec 1D loader

setup.cfg
This registers `moszviz` as a plugin for `glue`. It resolves #185.
=> Register glue plugin

mosviz/loaders/jwst_loaders.py
=> Rename level2 Data components

mosviz/data/ui/loader_selection.ui, mosviz/loaders/loader_selection.py
=> Fix loader ui title and lock the size of the text display

readthedocs.yml
There is a bug related to [read the docs and setuptools](https://github.com/rtfd/readthedocs.org/issues/5436). Update readthedocs.yml to reenable building of docs.
=> Fix Read the Docs Bug

.travis.yml, mosviz/__init__.py, mosviz/conftest.py, setup.cfg, tox.ini
This adds `pyqt5` to install_requires so it does not need to be installed by `conda`. It also addresses the issue that occurs on some OSX machines where `matplotlib` complains about Python not being installed as a framework.
=> Updates to make mosviz pip-installable

README.rst, docs/api.rst, docs/functionality.rst, docs/gettingstarted.rst, docs/index.rst, docs/installation.rst, docs/readingindata.rst
Adds a Deprecation Warning to the top of all doc pages directing users to Jdaviz for maintained mosviz development
=> Add Deprecation Warning to Docs
