spacetelescope/mosviz

docs/mosviz/notebooks/make_cutouts.ipynb, docs/mosviz/notebooks/make_rgb.ipynb
=> Verbiage cleanup on notebooks

README.rst, setup.cfg
Supersedes #24 due to merge conflicts after recent merges.
=> Minor RTD corrections

docs/readingindata.rst
I added instructions for actually starting the MOSViz Viewer in Glue.
=> Overview of Reading In Data

mosviz/loaders/mos_loaders.py
=> set uncertainty components to all be standard deviations

.travis.yml, docs/installation.rst, mosviz/widgets/toolbars.py, setup.py
This PR includes an initial stab at installation instructions, along with some usability tweaks.
=> Include install instructions

mosviz/viewers/mos_viewer.py, mosviz/widgets/plots.py
=> Fix compatibility with glueviz 0.10.x

mosviz/viewers/mos_viewer.py
This fixes various places where things were getting called multiple times, resulting in low performance. Some of the fixes were in glue itself, and therefore MOSViz only works well with the developer version of glue for now.
=> Improvements to performance

setup.cfg
=> Update version number to 0.2.0.dev

.travis.yml, mosviz/viewers/mos_viewer.py, setup.cfg
Closes #117. Remove SpecUtils dependency.
=> Remove specutil==0.2.2 from req

mosviz/loaders/loader_selection.py
=> Correct defaults now load in loader_selection gui

.travis.yml
This is a work in progress as I need to make sure that various files are correctly ignored
=> Upload coverage results to codecov

mosviz/cli.py
Remove unnecessary import statement.
=> Remove Outdated Glue Import 

.travis.yml, appveyor.yml, setup.cfg
=> Add install dependecy on regions

mosviz/conftest.py, mosviz/viewers/tests/test_mos_viewer.py
Reorganized test_mos_viewers.py, added exposure combobox reset state to conftest.
=> Reorganized test_mos_viewers

.gitignore, .rtd-environment.yml, .travis.yml, docs/installation.rst, mosviz/cli.py, mosviz/loaders/deimos_loaders.py, mosviz/loaders/loader_selection.py, mosviz/viewers/mos_viewer.py, mosviz/viewers/tests/test_mos_viewer.py, mosviz/widgets/toolbars.py, setup.cfg
This PR handles #120 and requires the latest master version of SpecViz (and may also require latest master version of [this SpecViz fork](https://github.com/nmearl/specviz)).
=> [WIP] Embed SpecViz 1D viewer in MOSViz

CHANGES.rst
Added in CHANGES.rst file to track the changes for each release.
Fixes #165
=> added in CHANGES.rst file

mosviz/loaders/jwst_loaders.py, mosviz/loaders/loader_selection.py, mosviz/loaders/utils.py, mosviz/viewers/mos_viewer.py
This PR introduces a level 2 loader as discussed in #170.
=> NIRSpec Level2 Loader

docs/installation.rst
Updated the docs to show how to install using conda from the nightly master.
=> Updated docs to show how to install nightly master

mosviz/loaders/loader_selection.py
Fixes https://github.com/spacetelescope/mosviz/issues/156
cc @robelgeda
=> Fix a bug that caused combo boxes to become empty when showing the wizard multiple times

mosviz/viewers/mos_viewer.py
fixes #203 
Bug happened because the image viewer was being hidden before the main UI appears.
Removed redundent code related to this bug.  
Use the following MOS Table for testing (test data = 'mosviz_nirspec_data_0.2'):
[no_cutout.txt](https://github.com/spacetelescope/mosviz/files/2933712/no_cutout.txt)
=> Fix problem displaying rows with no cutouts

mosviz/viewers/mos_viewer.py
The warnings weren't causing any crashes but might as well get rid of them!
=> Update data attributes to no longer emit deprecation warnings.

mosviz/tests/coveragerc
Let's see if this works, I imagine code-cov percentage should magically go up?
* That was a lie, looked closer at Dan's PR, and code coverage went down for that one too.
=> copying Dan's codecov fix so that it doesn't include test files

.travis.yml, mosviz/cli.py, mosviz/loaders/tests/test_load_NIRSpec_data.py, mosviz/viewers/mos_viewer.py, tox.ini
Soooo I have two working tests that do what Robel and I originally wanted.
Caveats:
* some of the stuff in mos_viewer.py is not pretty, but i think ultimately we need to refactor this stuff.
* I attached dan's jwst_data_test decorator so you could run these tests separately from the other unit tests, otherwise the None test causes seg faults.
* This usage of jwst_data_test should probably be documented, maybe just link to Dan's other dev doc in cubeviz? open to suggestions on this.
* This test is missing the check on the specviz viewer window.  Robel told me we can't do this at the moment because specviz is not re-hooked up to mosviz after recent specviz changes.
This closes #184.
=> first pass at adding some unit tests for JWST data. This closes #184

requirements.txt
Had to pin RTD pip back to 18.1. There's some issue with the latest pip and setuptools when working in a virtual env. https://github.com/rtfd/readthedocs.org/issues/5436
=> Rtd testing

README.rst
Directed users to Jdaviz in case they end up here via e.g. Google searching
=> Added note pointing to Jdaviz as the maintained repo
